esphome:
  name: ha-haysteamer
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80
  
ota:

dallas:
  - pin: GPIO4
# to get the sensor address, comment out the lines below this.
    update_interval: 15s

  
sensor:
  - platform: dallas
    address: 0x3d00000001b70628
    name: "Steamer temp"

  - platform: hx711
    name: "Water level"
    dout_pin: D0
    clk_pin: D1
    gain: 128
    filters:
     - calibrate_linear:
         - -107500 -> 0
         - -64400 -> 95
    update_interval: 10s
    unit_of_measurement: '%'


    

