esphome:
  name: ha-haysteamer
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80
  
ota:

dallas:
  - pin: GPIO4
    update_interval: 15s

  
sensor:
  - platform: dallas
    address: 0x3d00000001b70628
    name: "Steamer temp"
    

